ekf_local:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1

    two_d_mode: true

    publish_tf: true

    map_frame: map     # Local filter outputs in the odom frame
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # =========================================================
    # IMU (Gazebo)
    # =========================================================
    imu0: /demo/imu
    imu0_config: [false, false, false,   # x, y, z pos (IMU gives none)
                  true,  true,  true,    # roll, pitch, yaw
                  false, false, false,   # linear velocity
                  false, false, false,   # angular velocity
                  false, false, false]   # acceleration
    imu0_remove_gravitational_acceleration: true

    # =========================================================
    # Wheel Odometry (from Gazebo diff drive)
    # =========================================================
    odom0: /demo/odom
    odom0_config: [true,  true,  false,  # x, y, z (ignore z)
                   false, false, false,  # orientation from IMU instead
                   false, false, false,  # linear vel
                   false, false, true,   # yaw rate only
                   false, false, false]
